anger:
  keyframes:
  - duration: 0.0
    joints:
      lazy_susan: 505
      motor_back_left: 7
      motor_back_right: 123
      motor_front: 342
  - duration: 0.101
    joints:
      lazy_susan: 506
      motor_back_left: 6
      motor_back_right: 122
      motor_front: 344
  - duration: 0.102
    joints:
      lazy_susan: 508
      motor_back_left: 6
      motor_back_right: 122
      motor_front: 344
  - duration: 0.101
    joints:
      lazy_susan: 512
      motor_back_left: 6
      motor_back_right: 120
      motor_front: 345
  - duration: 0.1
    joints:
      lazy_susan: 514
      motor_back_left: 6
      motor_back_right: 121
      motor_front: 345
  - duration: 0.1
    joints:
      lazy_susan: 516
      motor_back_left: 7
      motor_back_right: 123
      motor_front: 342
  - duration: 0.101
    joints:
      lazy_susan: 502
      motor_back_left: 6
      motor_back_right: 131
      motor_front: 335
  - duration: 0.101
    joints:
      lazy_susan: 394
      motor_back_left: 23
      motor_back_right: 164
      motor_front: 285
  - duration: 0.102
    joints:
      lazy_susan: 247
      motor_back_left: 112
      motor_back_right: 155
      motor_front: 205
  - duration: 0.104
    joints:
      lazy_susan: 249
      motor_back_left: 159
      motor_back_right: 144
      motor_front: 175
  - duration: 0.1
    joints:
      lazy_susan: 373
      motor_back_left: 92
      motor_back_right: 162
      motor_front: 218
  - duration: 0.1
    joints:
      lazy_susan: 276
      motor_back_left: 102
      motor_back_right: 128
      motor_front: 246
  - duration: 0.101
    joints:
      lazy_susan: 264
      motor_back_left: 103
      motor_back_right: 115
      motor_front: 252
  - duration: 0.106
    joints:
      lazy_susan: 364
      motor_back_left: 83
      motor_back_right: 144
      motor_front: 245
  - duration: 0.104
    joints:
      lazy_susan: 229
      motor_back_left: 98
      motor_back_right: 134
      motor_front: 242
  - duration: 0.101
    joints:
      lazy_susan: 282
      motor_back_left: 93
      motor_back_right: 145
      motor_front: 235
  - duration: 0.102
    joints:
      lazy_susan: 357
      motor_back_left: 65
      motor_back_right: 152
      motor_front: 255
  - duration: 0.104
    joints:
      lazy_susan: 554
      motor_back_left: 3
      motor_back_right: 153
      motor_front: 316
  - duration: 0.102
    joints:
      lazy_susan: 745
      motor_back_left: 0
      motor_back_right: 189
      motor_front: 313
  - duration: 0.102
    joints:
      lazy_susan: 854
      motor_back_left: 0
      motor_back_right: 215
      motor_front: 291
  - duration: 0.101
    joints:
      lazy_susan: 810
      motor_back_left: 0
      motor_back_right: 225
      motor_front: 263
  - duration: 0.1
    joints:
      lazy_susan: 761
      motor_back_left: 33
      motor_back_right: 214
      motor_front: 225
  - duration: 0.101
    joints:
      lazy_susan: 874
      motor_back_left: 0
      motor_back_right: 220
      motor_front: 270
  - duration: 0.101
    joints:
      lazy_susan: 862
      motor_back_left: 17
      motor_back_right: 242
      motor_front: 220
  - duration: 0.102
    joints:
      lazy_susan: 843
      motor_back_left: 22
      motor_back_right: 223
      motor_front: 229
  - duration: 0.104
    joints:
      lazy_susan: 898
      motor_back_left: 0
      motor_back_right: 231
      motor_front: 248
  - duration: 0.105
    joints:
      lazy_susan: 837
      motor_back_left: 24
      motor_back_right: 224
      motor_front: 226
  - duration: 0.105
    joints:
      lazy_susan: 903
      motor_back_left: 0
      motor_back_right: 235
      motor_front: 248
  - duration: 0.102
    joints:
      lazy_susan: 872
      motor_back_left: 0
      motor_back_right: 243
      motor_front: 221
  - duration: 0.103
    joints:
      lazy_susan: 872
      motor_back_left: 0
      motor_back_right: 243
      motor_front: 221
  - duration: 0.102
    joints:
      lazy_susan: 598
      motor_back_left: 132
      motor_back_right: 148
      motor_front: 194
  - duration: 0.104
    joints:
      lazy_susan: 530
      motor_back_left: 111
      motor_back_right: 135
      motor_front: 228
  - duration: 0.101
    joints:
      lazy_susan: 497
      motor_back_left: 90
      motor_back_right: 119
      motor_front: 261
  - duration: 0.103
    joints:
      lazy_susan: 485
      motor_back_left: 69
      motor_back_right: 118
      motor_front: 285
  - duration: 0.101
    joints:
      lazy_susan: 485
      motor_back_left: 50
      motor_back_right: 119
      motor_front: 303
  - duration: 0.103
    joints:
      lazy_susan: 487
      motor_back_left: 33
      motor_back_right: 116
      motor_front: 323
  - duration: 0.103
    joints:
      lazy_susan: 491
      motor_back_left: 16
      motor_back_right: 113
      motor_front: 342
  - duration: 0.105
    joints:
      lazy_susan: 491
      motor_back_left: 7
      motor_back_right: 115
      motor_front: 350
  - duration: 0.104
    joints:
      lazy_susan: 490
      motor_back_left: 3
      motor_back_right: 119
      motor_front: 350
  - duration: 0.104
    joints:
      lazy_susan: 490
      motor_back_left: 0
      motor_back_right: 126
      motor_front: 350
  - duration: 0.104
    joints:
      lazy_susan: 492
      motor_back_left: 0
      motor_back_right: 126
      motor_front: 351
  - duration: 0.105
    joints:
      lazy_susan: 495
      motor_back_left: 0
      motor_back_right: 125
      motor_front: 350
  - duration: 0.105
    joints:
      lazy_susan: 494
      motor_back_left: 0
      motor_back_right: 124
      motor_front: 351
  - duration: 0.104
    joints:
      lazy_susan: 494
      motor_back_left: 0
      motor_back_right: 124
      motor_front: 352
  - duration: 0.105
    joints:
      lazy_susan: 495
      motor_back_left: 0
      motor_back_right: 125
      motor_front: 351
  - duration: 0.104
    joints:
      lazy_susan: 496
      motor_back_left: 0
      motor_back_right: 122
      motor_front: 353
  - duration: 0.104
    joints:
      lazy_susan: 497
      motor_back_left: 0
      motor_back_right: 123
      motor_front: 353
  - duration: 0.102
    joints:
      lazy_susan: 499
      motor_back_left: 0
      motor_back_right: 122
      motor_front: 354
  - duration: 0.101
    joints:
      lazy_susan: 499
      motor_back_left: 0
      motor_back_right: 121
      motor_front: 356
  - duration: 0.105
    joints:
      lazy_susan: 495
      motor_back_left: 0
      motor_back_right: 122
      motor_front: 355
  - duration: 0.105
    joints:
      lazy_susan: 494
      motor_back_left: 0
      motor_back_right: 122
      motor_front: 356
  - duration: 0.104
    joints:
      lazy_susan: 494
      motor_back_left: 0
      motor_back_right: 121
      motor_front: 359
