bounce_smooth:
  keyframes:
  - duration: 0.0
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 158
      motor_back_right: 273
      motor_front: 492
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 158
      motor_back_right: 273
      motor_front: 492
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 76
      motor_back_right: 191
      motor_front: 410
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 27
      motor_back_right: 142
      motor_front: 361
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 93
      motor_front: 312
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 93
      motor_front: 312
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 27
      motor_back_right: 142
      motor_front: 361
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 76
      motor_back_right: 191
      motor_front: 410
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 148
      motor_back_right: 263
      motor_front: 482
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 171
      motor_back_right: 286
      motor_front: 505
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 148
      motor_back_right: 263
      motor_front: 482
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 76
      motor_back_right: 191
      motor_front: 410
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 27
      motor_back_right: 142
      motor_front: 361
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 93
      motor_front: 312
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 78
      motor_front: 297
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 113
      motor_front: 332
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 33
      motor_back_right: 148
      motor_front: 367
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 66
      motor_back_right: 181
      motor_front: 400
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 82
      motor_back_right: 197
      motor_front: 416
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 96
      motor_back_right: 211
      motor_front: 430
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 109
      motor_back_right: 224
      motor_front: 443
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 109
      motor_back_right: 224
      motor_front: 443
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 96
      motor_back_right: 211
      motor_front: 430
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 82
      motor_back_right: 197
      motor_front: 416
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 66
      motor_back_right: 181
      motor_front: 400
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 33
      motor_back_right: 148
      motor_front: 367
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 113
      motor_front: 332
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 78
      motor_front: 297
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 64
      motor_front: 283
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 84
      motor_front: 303
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 103
      motor_front: 322
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 8
      motor_back_right: 123
      motor_front: 342
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 17
      motor_back_right: 132
      motor_front: 351
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 27
      motor_back_right: 142
      motor_front: 361
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 37
      motor_back_right: 152
      motor_front: 371
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 47
      motor_back_right: 162
      motor_front: 381
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 37
      motor_back_right: 152
      motor_front: 371
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 27
      motor_back_right: 142
      motor_front: 361
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 17
      motor_back_right: 132
      motor_front: 351
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 8
      motor_back_right: 123
      motor_front: 342
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 103
      motor_front: 322
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 84
      motor_front: 303
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 64
      motor_front: 283
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 60
      motor_front: 279
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 74
      motor_front: 293
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 87
      motor_front: 306
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 103
      motor_front: 322
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 109
      motor_front: 328
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 113
      motor_front: 332
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 4
      motor_back_right: 119
      motor_front: 338
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 8
      motor_back_right: 123
      motor_front: 342
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 4
      motor_back_right: 119
      motor_front: 338
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 113
      motor_front: 332
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 109
      motor_front: 328
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 103
      motor_front: 322
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 87
      motor_front: 306
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 74
      motor_front: 293
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 60
      motor_front: 279
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 54
      motor_front: 273
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 64
      motor_front: 283
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 74
      motor_front: 293
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 84
      motor_front: 303
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 74
      motor_front: 293
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 64
      motor_front: 283
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 54
      motor_front: 273
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 45
      motor_front: 264
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 93
      motor_front: 312
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 27
      motor_back_right: 142
      motor_front: 361
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 76
      motor_back_right: 191
      motor_front: 410
  - duration: 0.075
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
