calm:
  keyframes:
  - duration: 1.5
    joints:
      lazy_susan: 512
      motor_back_left: 18
      motor_back_right: 133
      motor_front: 352
  - duration: 1.5
    joints:
      lazy_susan: 512
      motor_back_left: 38
      motor_back_right: 153
      motor_front: 372
  - duration: 1.5
    joints:
      lazy_susan: 512
      motor_back_left: 18
      motor_back_right: 133
      motor_front: 352
