dance1_1:
  keyframes:
  - duration: 0.0
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 181
      motor_front: 439
  - duration: 0.265
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.266
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 181
      motor_front: 439
  - duration: 0.265
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.266
    joints:
      lazy_susan: 512
      motor_back_left: 66
      motor_back_right: 240
      motor_front: 439
  - duration: 0.265
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.266
    joints:
      lazy_susan: 512
      motor_back_left: 66
      motor_back_right: 240
      motor_front: 439
  - duration: 0.265
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.266
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 181
      motor_front: 439
  - duration: 0.265
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.266
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 181
      motor_front: 439
  - duration: 0.265
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.266
    joints:
      lazy_susan: 512
      motor_back_left: 66
      motor_back_right: 240
      motor_front: 439
  - duration: 0.265
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.266
    joints:
      lazy_susan: 512
      motor_back_left: 66
      motor_back_right: 240
      motor_front: 439
  - duration: 0.265
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
