excited:
  keyframes:
  - duration: 0.15
    joints:
      lazy_susan: 450
      motor_back_left: 0
      motor_back_right: 83
      motor_front: 302
  - duration: 0.15
    joints:
      lazy_susan: 574
      motor_back_left: 0
      motor_back_right: 63
      motor_front: 282
  - duration: 0.15
    joints:
      lazy_susan: 450
      motor_back_left: 0
      motor_back_right: 83
      motor_front: 302
  - duration: 0.2
    joints:
      lazy_susan: 512
      motor_back_left: 18
      motor_back_right: 133
      motor_front: 352
