fear:
  keyframes:
  - duration: 0.0
    joints:
      lazy_susan: 501
      motor_back_left: 0
      motor_back_right: 123
      motor_front: 376
  - duration: 0.104
    joints:
      lazy_susan: 501
      motor_back_left: 0
      motor_back_right: 120
      motor_front: 376
  - duration: 0.101
    joints:
      lazy_susan: 502
      motor_back_left: 0
      motor_back_right: 123
      motor_front: 371
  - duration: 0.102
    joints:
      lazy_susan: 502
      motor_back_left: 0
      motor_back_right: 128
      motor_front: 365
  - duration: 0.102
    joints:
      lazy_susan: 502
      motor_back_left: 0
      motor_back_right: 129
      motor_front: 365
  - duration: 0.105
    joints:
      lazy_susan: 502
      motor_back_left: 0
      motor_back_right: 129
      motor_front: 365
  - duration: 0.101
    joints:
      lazy_susan: 504
      motor_back_left: 0
      motor_back_right: 129
      motor_front: 361
  - duration: 0.103
    joints:
      lazy_susan: 504
      motor_back_left: 0
      motor_back_right: 132
      motor_front: 355
  - duration: 0.1
    joints:
      lazy_susan: 504
      motor_back_left: 0
      motor_back_right: 131
      motor_front: 341
  - duration: 0.105
    joints:
      lazy_susan: 507
      motor_back_left: 0
      motor_back_right: 110
      motor_front: 377
  - duration: 0.102
    joints:
      lazy_susan: 506
      motor_back_left: 0
      motor_back_right: 20
      motor_front: 505
  - duration: 0.103
    joints:
      lazy_susan: 506
      motor_back_left: 0
      motor_back_right: 20
      motor_front: 505
  - duration: 0.104
    joints:
      lazy_susan: 476
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 505
  - duration: 0.103
    joints:
      lazy_susan: 482
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 505
  - duration: 0.105
    joints:
      lazy_susan: 481
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 505
  - duration: 0.104
    joints:
      lazy_susan: 462
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 505
  - duration: 0.104
    joints:
      lazy_susan: 459
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 505
  - duration: 0.103
    joints:
      lazy_susan: 381
      motor_back_left: 0
      motor_back_right: 33
      motor_front: 505
  - duration: 0.104
    joints:
      lazy_susan: 238
      motor_back_left: 0
      motor_back_right: 215
      motor_front: 505
  - duration: 0.104
    joints:
      lazy_susan: 159
      motor_back_left: 0
      motor_back_right: 252
      motor_front: 505
  - duration: 0.102
    joints:
      lazy_susan: 180
      motor_back_left: 0
      motor_back_right: 247
      motor_front: 505
  - duration: 0.101
    joints:
      lazy_susan: 328
      motor_back_left: 0
      motor_back_right: 210
      motor_front: 505
  - duration: 0.102
    joints:
      lazy_susan: 328
      motor_back_left: 0
      motor_back_right: 210
      motor_front: 505
  - duration: 0.105
    joints:
      lazy_susan: 567
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 505
  - duration: 0.106
    joints:
      lazy_susan: 732
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 505
  - duration: 0.1
    joints:
      lazy_susan: 710
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 505
  - duration: 0.1
    joints:
      lazy_susan: 551
      motor_back_left: 0
      motor_back_right: 17
      motor_front: 505
  - duration: 0.101
    joints:
      lazy_susan: 471
      motor_back_left: 0
      motor_back_right: 34
      motor_front: 505
  - duration: 0.101
    joints:
      lazy_susan: 425
      motor_back_left: 0
      motor_back_right: 37
      motor_front: 505
  - duration: 0.102
    joints:
      lazy_susan: 402
      motor_back_left: 0
      motor_back_right: 25
      motor_front: 505
  - duration: 0.103
    joints:
      lazy_susan: 420
      motor_back_left: 0
      motor_back_right: 6
      motor_front: 505
  - duration: 0.101
    joints:
      lazy_susan: 468
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 505
  - duration: 0.1
    joints:
      lazy_susan: 500
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 505
  - duration: 0.101
    joints:
      lazy_susan: 509
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 505
  - duration: 0.103
    joints:
      lazy_susan: 510
      motor_back_left: 0
      motor_back_right: 8
      motor_front: 505
  - duration: 0.104
    joints:
      lazy_susan: 514
      motor_back_left: 0
      motor_back_right: 33
      motor_front: 505
  - duration: 0.103
    joints:
      lazy_susan: 517
      motor_back_left: 0
      motor_back_right: 61
      motor_front: 505
  - duration: 0.101
    joints:
      lazy_susan: 520
      motor_back_left: 0
      motor_back_right: 82
      motor_front: 492
  - duration: 0.101
    joints:
      lazy_susan: 522
      motor_back_left: 0
      motor_back_right: 101
      motor_front: 455
  - duration: 0.101
    joints:
      lazy_susan: 522
      motor_back_left: 0
      motor_back_right: 118
      motor_front: 423
  - duration: 0.105
    joints:
      lazy_susan: 517
      motor_back_left: 0
      motor_back_right: 154
      motor_front: 389
  - duration: 0.105
    joints:
      lazy_susan: 518
      motor_back_left: 0
      motor_back_right: 152
      motor_front: 384
  - duration: 0.101
    joints:
      lazy_susan: 521
      motor_back_left: 0
      motor_back_right: 148
      motor_front: 374
  - duration: 0.1
    joints:
      lazy_susan: 521
      motor_back_left: 0
      motor_back_right: 148
      motor_front: 374
  - duration: 0.101
    joints:
      lazy_susan: 522
      motor_back_left: 0
      motor_back_right: 144
      motor_front: 360
  - duration: 0.1
    joints:
      lazy_susan: 522
      motor_back_left: 0
      motor_back_right: 140
      motor_front: 360
  - duration: 0.104
    joints:
      lazy_susan: 521
      motor_back_left: 0
      motor_back_right: 135
      motor_front: 363
  - duration: 0.103
    joints:
      lazy_susan: 519
      motor_back_left: 0
      motor_back_right: 133
      motor_front: 364
  - duration: 0.103
    joints:
      lazy_susan: 518
      motor_back_left: 0
      motor_back_right: 128
      motor_front: 367
  - duration: 0.103
    joints:
      lazy_susan: 519
      motor_back_left: 0
      motor_back_right: 127
      motor_front: 368
  - duration: 0.103
    joints:
      lazy_susan: 519
      motor_back_left: 0
      motor_back_right: 124
      motor_front: 368
  - duration: 0.101
    joints:
      lazy_susan: 519
      motor_back_left: 0
      motor_back_right: 120
      motor_front: 371
