happy:
  keyframes:
  - duration: 0.0
    joints:
      lazy_susan: 493
      motor_back_left: 0
      motor_back_right: 107
      motor_front: 333
  - duration: 0.103
    joints:
      lazy_susan: 493
      motor_back_left: 1
      motor_back_right: 106
      motor_front: 332
  - duration: 0.102
    joints:
      lazy_susan: 492
      motor_back_left: 0
      motor_back_right: 107
      motor_front: 332
  - duration: 0.101
    joints:
      lazy_susan: 492
      motor_back_left: 1
      motor_back_right: 106
      motor_front: 333
  - duration: 0.103
    joints:
      lazy_susan: 492
      motor_back_left: 2
      motor_back_right: 106
      motor_front: 332
  - duration: 0.104
    joints:
      lazy_susan: 492
      motor_back_left: 1
      motor_back_right: 105
      motor_front: 333
  - duration: 0.104
    joints:
      lazy_susan: 493
      motor_back_left: 1
      motor_back_right: 106
      motor_front: 333
  - duration: 0.105
    joints:
      lazy_susan: 495
      motor_back_left: 0
      motor_back_right: 106
      motor_front: 332
  - duration: 0.104
    joints:
      lazy_susan: 499
      motor_back_left: 0
      motor_back_right: 99
      motor_front: 328
  - duration: 0.104
    joints:
      lazy_susan: 502
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 192
  - duration: 0.105
    joints:
      lazy_susan: 503
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 202
  - duration: 0.105
    joints:
      lazy_susan: 506
      motor_back_left: 114
      motor_back_right: 226
      motor_front: 444
  - duration: 0.103
    joints:
      lazy_susan: 507
      motor_back_left: 171
      motor_back_right: 284
      motor_front: 505
  - duration: 0.1
    joints:
      lazy_susan: 504
      motor_back_left: 72
      motor_back_right: 180
      motor_front: 401
  - duration: 0.101
    joints:
      lazy_susan: 504
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 214
  - duration: 0.103
    joints:
      lazy_susan: 507
      motor_back_left: 0
      motor_back_right: 29
      motor_front: 245
  - duration: 0.105
    joints:
      lazy_susan: 506
      motor_back_left: 127
      motor_back_right: 236
      motor_front: 454
  - duration: 0.103
    joints:
      lazy_susan: 503
      motor_back_left: 22
      motor_back_right: 133
      motor_front: 350
  - duration: 0.104
    joints:
      lazy_susan: 506
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 188
  - duration: 0.103
    joints:
      lazy_susan: 507
      motor_back_left: 72
      motor_back_right: 181
      motor_front: 400
  - duration: 0.1
    joints:
      lazy_susan: 506
      motor_back_left: 149
      motor_back_right: 257
      motor_front: 476
  - duration: 0.105
    joints:
      lazy_susan: 504
      motor_back_left: 54
      motor_back_right: 165
      motor_front: 384
  - duration: 0.1
    joints:
      lazy_susan: 503
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 210
  - duration: 0.1
    joints:
      lazy_susan: 506
      motor_back_left: 0
      motor_back_right: 90
      motor_front: 307
  - duration: 0.102
    joints:
      lazy_susan: 506
      motor_back_left: 127
      motor_back_right: 237
      motor_front: 453
  - duration: 0.104
    joints:
      lazy_susan: 505
      motor_back_left: 104
      motor_back_right: 216
      motor_front: 431
  - duration: 0.104
    joints:
      lazy_susan: 504
      motor_back_left: 0
      motor_back_right: 2
      motor_front: 220
  - duration: 0.105
    joints:
      lazy_susan: 507
      motor_back_left: 0
      motor_back_right: 0
      motor_front: 212
  - duration: 0.105
    joints:
      lazy_susan: 507
      motor_back_left: 95
      motor_back_right: 203
      motor_front: 420
  - duration: 0.105
    joints:
      lazy_susan: 505
      motor_back_left: 0
      motor_back_right: 104
      motor_front: 324
  - duration: 0.103
    joints:
      lazy_susan: 506
      motor_back_left: 0
      motor_back_right: 60
      motor_front: 279
  - duration: 0.105
    joints:
      lazy_susan: 509
      motor_back_left: 85
      motor_back_right: 192
      motor_front: 409
  - duration: 0.105
    joints:
      lazy_susan: 506
      motor_back_left: 99
      motor_back_right: 209
      motor_front: 427
  - duration: 0.104
    joints:
      lazy_susan: 506
      motor_back_left: 23
      motor_back_right: 131
      motor_front: 351
  - duration: 0.104
    joints:
      lazy_susan: 505
      motor_back_left: 0
      motor_back_right: 92
      motor_front: 313
  - duration: 0.104
    joints:
      lazy_susan: 505
      motor_back_left: 0
      motor_back_right: 87
      motor_front: 307
  - duration: 0.103
    joints:
      lazy_susan: 506
      motor_back_left: 0
      motor_back_right: 93
      motor_front: 313
  - duration: 0.103
    joints:
      lazy_susan: 506
      motor_back_left: 0
      motor_back_right: 99
      motor_front: 319
  - duration: 0.103
    joints:
      lazy_susan: 506
      motor_back_left: 0
      motor_back_right: 109
      motor_front: 331
  - duration: 0.104
    joints:
      lazy_susan: 506
      motor_back_left: 0
      motor_back_right: 109
      motor_front: 330
  - duration: 0.106
    joints:
      lazy_susan: 510
      motor_back_left: 4
      motor_back_right: 114
      motor_front: 337
  - duration: 0.103
    joints:
      lazy_susan: 510
      motor_back_left: 4
      motor_back_right: 114
      motor_front: 337
  - duration: 0.104
    joints:
      lazy_susan: 507
      motor_back_left: 6
      motor_back_right: 112
      motor_front: 338
  - duration: 0.103
    joints:
      lazy_susan: 503
      motor_back_left: 6
      motor_back_right: 113
      motor_front: 337
  - duration: 0.104
    joints:
      lazy_susan: 503
      motor_back_left: 5
      motor_back_right: 112
      motor_front: 338
