idle:
  keyframes:
  - duration: 2.0
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 113
      motor_front: 332
  - duration: 2.5
    joints:
      lazy_susan: 512
      motor_back_left: 70
      motor_back_right: 183
      motor_front: 390
  - duration: 2.0
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 113
      motor_front: 332
