look_up:
  keyframes:
    - joints:
        motor_front: 252
        motor_back_left: 18
        motor_back_right: 133
        lazy_susan: 512
      duration: 0.5
    - joints:
        motor_front: 352
        motor_back_left: 18
        motor_back_right: 133
        lazy_susan: 512
      duration: 0.5
