look_down:
  keyframes:
  - duration: 0.5
    joints:
      lazy_susan: 512
      motor_back_left: 0
      motor_back_right: 83
      motor_front: 552
  - duration: 0.5
    joints:
      lazy_susan: 512
      motor_back_left: 18
      motor_back_right: 133
      motor_front: 352
