reset:
  keyframes:
  - duration: 0.0
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
  - duration: 0.05
    joints:
      lazy_susan: 512
      motor_back_left: 125
      motor_back_right: 240
      motor_front: 459
