sad:
  keyframes:
  - duration: 0.0
    joints:
      lazy_susan: 514
      motor_back_left: 0
      motor_back_right: 123
      motor_front: 367
  - duration: 0.103
    joints:
      lazy_susan: 514
      motor_back_left: 0
      motor_back_right: 123
      motor_front: 367
  - duration: 0.1
    joints:
      lazy_susan: 515
      motor_back_left: 0
      motor_back_right: 124
      motor_front: 363
  - duration: 0.102
    joints:
      lazy_susan: 515
      motor_back_left: 0
      motor_back_right: 123
      motor_front: 363
  - duration: 0.103
    joints:
      lazy_susan: 515
      motor_back_left: 0
      motor_back_right: 123
      motor_front: 362
  - duration: 0.101
    joints:
      lazy_susan: 515
      motor_back_left: 0
      motor_back_right: 122
      motor_front: 363
  - duration: 0.101
    joints:
      lazy_susan: 515
      motor_back_left: 0
      motor_back_right: 121
      motor_front: 366
  - duration: 0.1
    joints:
      lazy_susan: 514
      motor_back_left: 0
      motor_back_right: 118
      motor_front: 370
  - duration: 0.102
    joints:
      lazy_susan: 514
      motor_back_left: 0
      motor_back_right: 116
      motor_front: 375
  - duration: 0.105
    joints:
      lazy_susan: 515
      motor_back_left: 0
      motor_back_right: 113
      motor_front: 381
  - duration: 0.101
    joints:
      lazy_susan: 515
      motor_back_left: 0
      motor_back_right: 108
      motor_front: 391
  - duration: 0.105
    joints:
      lazy_susan: 516
      motor_back_left: 0
      motor_back_right: 100
      motor_front: 408
  - duration: 0.103
    joints:
      lazy_susan: 518
      motor_back_left: 0
      motor_back_right: 78
      motor_front: 463
  - duration: 0.101
    joints:
      lazy_susan: 518
      motor_back_left: 0
      motor_back_right: 68
      motor_front: 485
  - duration: 0.101
    joints:
      lazy_susan: 520
      motor_back_left: 0
      motor_back_right: 57
      motor_front: 502
  - duration: 0.101
    joints:
      lazy_susan: 520
      motor_back_left: 0
      motor_back_right: 49
      motor_front: 505
  - duration: 0.104
    joints:
      lazy_susan: 521
      motor_back_left: 0
      motor_back_right: 46
      motor_front: 505
  - duration: 0.1
    joints:
      lazy_susan: 521
      motor_back_left: 0
      motor_back_right: 46
      motor_front: 505
  - duration: 0.106
    joints:
      lazy_susan: 521
      motor_back_left: 0
      motor_back_right: 47
      motor_front: 505
  - duration: 0.103
    joints:
      lazy_susan: 522
      motor_back_left: 0
      motor_back_right: 54
      motor_front: 499
  - duration: 0.1
    joints:
      lazy_susan: 523
      motor_back_left: 0
      motor_back_right: 71
      motor_front: 469
  - duration: 0.105
    joints:
      lazy_susan: 525
      motor_back_left: 0
      motor_back_right: 89
      motor_front: 433
  - duration: 0.105
    joints:
      lazy_susan: 527
      motor_back_left: 0
      motor_back_right: 106
      motor_front: 399
  - duration: 0.101
    joints:
      lazy_susan: 533
      motor_back_left: 24
      motor_back_right: 153
      motor_front: 296
  - duration: 0.104
    joints:
      lazy_susan: 536
      motor_back_left: 76
      motor_back_right: 183
      motor_front: 213
  - duration: 0.104
    joints:
      lazy_susan: 539
      motor_back_left: 128
      motor_back_right: 210
      motor_front: 134
  - duration: 0.104
    joints:
      lazy_susan: 539
      motor_back_left: 170
      motor_back_right: 225
      motor_front: 78
  - duration: 0.101
    joints:
      lazy_susan: 543
      motor_back_left: 171
      motor_back_right: 235
      motor_front: 55
  - duration: 0.105
    joints:
      lazy_susan: 558
      motor_back_left: 171
      motor_back_right: 244
      motor_front: 56
  - duration: 0.103
    joints:
      lazy_susan: 563
      motor_back_left: 168
      motor_back_right: 246
      motor_front: 59
  - duration: 0.103
    joints:
      lazy_susan: 569
      motor_back_left: 162
      motor_back_right: 246
      motor_front: 65
  - duration: 0.102
    joints:
      lazy_susan: 578
      motor_back_left: 155
      motor_back_right: 245
      motor_front: 72
  - duration: 0.105
    joints:
      lazy_susan: 590
      motor_back_left: 143
      motor_back_right: 252
      motor_front: 77
  - duration: 0.103
    joints:
      lazy_susan: 601
      motor_back_left: 132
      motor_back_right: 262
      motor_front: 78
  - duration: 0.103
    joints:
      lazy_susan: 595
      motor_back_left: 134
      motor_back_right: 265
      motor_front: 73
  - duration: 0.102
    joints:
      lazy_susan: 519
      motor_back_left: 170
      motor_back_right: 233
      motor_front: 69
  - duration: 0.105
    joints:
      lazy_susan: 487
      motor_back_left: 171
      motor_back_right: 219
      motor_front: 71
  - duration: 0.104
    joints:
      lazy_susan: 493
      motor_back_left: 171
      motor_back_right: 223
      motor_front: 74
  - duration: 0.102
    joints:
      lazy_susan: 534
      motor_back_left: 152
      motor_back_right: 242
      motor_front: 78
  - duration: 0.104
    joints:
      lazy_susan: 572
      motor_back_left: 129
      motor_back_right: 254
      motor_front: 89
  - duration: 0.105
    joints:
      lazy_susan: 580
      motor_back_left: 127
      motor_back_right: 251
      motor_front: 94
  - duration: 0.103
    joints:
      lazy_susan: 531
      motor_back_left: 151
      motor_back_right: 227
      motor_front: 95
  - duration: 0.104
    joints:
      lazy_susan: 495
      motor_back_left: 162
      motor_back_right: 211
      motor_front: 99
  - duration: 0.1
    joints:
      lazy_susan: 510
      motor_back_left: 160
      motor_back_right: 217
      motor_front: 96
  - duration: 0.101
    joints:
      lazy_susan: 574
      motor_back_left: 135
      motor_back_right: 246
      motor_front: 91
  - duration: 0.102
    joints:
      lazy_susan: 589
      motor_back_left: 118
      motor_back_right: 257
      motor_front: 97
  - duration: 0.105
    joints:
      lazy_susan: 495
      motor_back_left: 171
      motor_back_right: 205
      motor_front: 97
  - duration: 0.103
    joints:
      lazy_susan: 495
      motor_back_left: 168
      motor_back_right: 204
      motor_front: 101
  - duration: 0.1
    joints:
      lazy_susan: 552
      motor_back_left: 138
      motor_back_right: 234
      motor_front: 100
  - duration: 0.104
    joints:
      lazy_susan: 594
      motor_back_left: 112
      motor_back_right: 257
      motor_front: 103
  - duration: 0.101
    joints:
      lazy_susan: 553
      motor_back_left: 135
      motor_back_right: 243
      motor_front: 94
  - duration: 0.104
    joints:
      lazy_susan: 505
      motor_back_left: 158
      motor_back_right: 212
      motor_front: 102
  - duration: 0.101
    joints:
      lazy_susan: 497
      motor_back_left: 164
      motor_back_right: 211
      motor_front: 98
  - duration: 0.102
    joints:
      lazy_susan: 540
      motor_back_left: 144
      motor_back_right: 239
      motor_front: 90
  - duration: 0.1
    joints:
      lazy_susan: 586
      motor_back_left: 114
      motor_back_right: 263
      motor_front: 95
  - duration: 0.104
    joints:
      lazy_susan: 593
      motor_back_left: 106
      motor_back_right: 267
      motor_front: 100
  - duration: 0.101
    joints:
      lazy_susan: 569
      motor_back_left: 127
      motor_back_right: 253
      motor_front: 92
  - duration: 0.101
    joints:
      lazy_susan: 552
      motor_back_left: 141
      motor_back_right: 240
      motor_front: 91
  - duration: 0.102
    joints:
      lazy_susan: 546
      motor_back_left: 144
      motor_back_right: 240
      motor_front: 88
  - duration: 0.104
    joints:
      lazy_susan: 550
      motor_back_left: 158
      motor_back_right: 246
      motor_front: 68
  - duration: 0.102
    joints:
      lazy_susan: 552
      motor_back_left: 171
      motor_back_right: 249
      motor_front: 52
  - duration: 0.1
    joints:
      lazy_susan: 557
      motor_back_left: 171
      motor_back_right: 254
      motor_front: 47
  - duration: 0.101
    joints:
      lazy_susan: 560
      motor_back_left: 164
      motor_back_right: 252
      motor_front: 56
  - duration: 0.1
    joints:
      lazy_susan: 562
      motor_back_left: 148
      motor_back_right: 249
      motor_front: 76
  - duration: 0.103
    joints:
      lazy_susan: 562
      motor_back_left: 148
      motor_back_right: 249
      motor_front: 76
  - duration: 0.1
    joints:
      lazy_susan: 563
      motor_back_left: 113
      motor_back_right: 230
      motor_front: 129
  - duration: 0.106
    joints:
      lazy_susan: 563
      motor_back_left: 99
      motor_back_right: 220
      motor_front: 154
  - duration: 0.103
    joints:
      lazy_susan: 564
      motor_back_left: 78
      motor_back_right: 209
      motor_front: 185
  - duration: 0.103
    joints:
      lazy_susan: 562
      motor_back_left: 56
      motor_back_right: 193
      motor_front: 222
  - duration: 0.102
    joints:
      lazy_susan: 561
      motor_back_left: 36
      motor_back_right: 184
      motor_front: 253
  - duration: 0.101
    joints:
      lazy_susan: 562
      motor_back_left: 17
      motor_back_right: 172
      motor_front: 283
  - duration: 0.105
    joints:
      lazy_susan: 561
      motor_back_left: 9
      motor_back_right: 165
      motor_front: 299
  - duration: 0.104
    joints:
      lazy_susan: 559
      motor_back_left: 0
      motor_back_right: 155
      motor_front: 318
  - duration: 0.1
    joints:
      lazy_susan: 558
      motor_back_left: 0
      motor_back_right: 158
      motor_front: 315
  - duration: 0.105
    joints:
      lazy_susan: 556
      motor_back_left: 0
      motor_back_right: 160
      motor_front: 316
  - duration: 0.103
    joints:
      lazy_susan: 553
      motor_back_left: 0
      motor_back_right: 157
      motor_front: 324
  - duration: 0.101
    joints:
      lazy_susan: 551
      motor_back_left: 0
      motor_back_right: 158
      motor_front: 324
  - duration: 0.105
    joints:
      lazy_susan: 549
      motor_back_left: 0
      motor_back_right: 157
      motor_front: 329
  - duration: 0.1
    joints:
      lazy_susan: 548
      motor_back_left: 0
      motor_back_right: 158
      motor_front: 333
  - duration: 0.105
    joints:
      lazy_susan: 547
      motor_back_left: 0
      motor_back_right: 157
      motor_front: 337
