'yes':
  keyframes:
  - duration: 0.0
    joints:
      lazy_susan: 503
      motor_back_left: 0
      motor_back_right: 131
      motor_front: 341
  - duration: 0.105
    joints:
      lazy_susan: 503
      motor_back_left: 0
      motor_back_right: 129
      motor_front: 344
  - duration: 0.102
    joints:
      lazy_susan: 502
      motor_back_left: 0
      motor_back_right: 131
      motor_front: 341
  - duration: 0.101
    joints:
      lazy_susan: 502
      motor_back_left: 0
      motor_back_right: 131
      motor_front: 340
  - duration: 0.101
    joints:
      lazy_susan: 502
      motor_back_left: 0
      motor_back_right: 130
      motor_front: 342
  - duration: 0.101
    joints:
      lazy_susan: 502
      motor_back_left: 0
      motor_back_right: 129
      motor_front: 343
  - duration: 0.1
    joints:
      lazy_susan: 502
      motor_back_left: 0
      motor_back_right: 130
      motor_front: 342
  - duration: 0.105
    joints:
      lazy_susan: 505
      motor_back_left: 26
      motor_back_right: 145
      motor_front: 302
  - duration: 0.106
    joints:
      lazy_susan: 505
      motor_back_left: 26
      motor_back_right: 145
      motor_front: 302
  - duration: 0.1
    joints:
      lazy_susan: 504
      motor_back_left: 72
      motor_back_right: 159
      motor_front: 242
  - duration: 0.105
    joints:
      lazy_susan: 508
      motor_back_left: 34
      motor_back_right: 142
      motor_front: 296
  - duration: 0.105
    joints:
      lazy_susan: 507
      motor_back_left: 0
      motor_back_right: 109
      motor_front: 387
  - duration: 0.101
    joints:
      lazy_susan: 509
      motor_back_left: 0
      motor_back_right: 124
      motor_front: 351
  - duration: 0.101
    joints:
      lazy_susan: 509
      motor_back_left: 38
      motor_back_right: 145
      motor_front: 289
  - duration: 0.104
    joints:
      lazy_susan: 508
      motor_back_left: 71
      motor_back_right: 166
      motor_front: 235
  - duration: 0.103
    joints:
      lazy_susan: 507
      motor_back_left: 65
      motor_back_right: 160
      motor_front: 247
  - duration: 0.101
    joints:
      lazy_susan: 506
      motor_back_left: 47
      motor_back_right: 143
      motor_front: 283
  - duration: 0.102
    joints:
      lazy_susan: 506
      motor_back_left: 18
      motor_back_right: 125
      motor_front: 329
  - duration: 0.102
    joints:
      lazy_susan: 506
      motor_back_left: 9
      motor_back_right: 118
      motor_front: 346
  - duration: 0.101
    joints:
      lazy_susan: 505
      motor_back_left: 3
      motor_back_right: 116
      motor_front: 353
  - duration: 0.105
    joints:
      lazy_susan: 505
      motor_back_left: 5
      motor_back_right: 118
      motor_front: 350
  - duration: 0.102
    joints:
      lazy_susan: 506
      motor_back_left: 6
      motor_back_right: 125
      motor_front: 341
  - duration: 0.1
    joints:
      lazy_susan: 506
      motor_back_left: 7
      motor_back_right: 128
      motor_front: 337
  - duration: 0.1
    joints:
      lazy_susan: 505
      motor_back_left: 7
      motor_back_right: 128
      motor_front: 337
  - duration: 0.101
    joints:
      lazy_susan: 506
      motor_back_left: 4
      motor_back_right: 130
      motor_front: 337
